# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'Shougo/defx.nvim' # you need pynvim

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'


[[plugins]]
repo = 'github/copilot.vim'
# on_ft = ['python', 'javascript', 'typescript']
hook_add = '''
  let g:copilot_enable = 1
'''
# https://docs.github.com/en/enterprise-cloud@latest/copilot/getting-started-with-github-copilot/getting-started-with-github-copilot-in-neovim

#========== Wakatimeプラグイン ==========
[[plugins]]
repo = 'wakatime/vim-wakatime'

#========== vim-lsp とその関連プラグイン ==========
#vim-lspとLanguage Serverの連携に必要なプラグイン群
#:call lsp#enable() :call lsp#disable()
#:call dein#recache_runtimepath() キャッシュ
#[[plugins]]
#repo = 'prabirshrestha/vim-lsp'
#
#[[plugins]]
#repo = 'mattn/vim-lsp-settings'
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'


#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'
#hook_add = '''
#" Enable flake8(~/.config/flake8 or PJ/.flake8) TODO black
#let g:lsp_settings = {
#\  'pylsp-all': {
#\    'workspace_config': {
#\      'pylsp': {
#\        'configurationSources': ['flake8'],
#\        'plugins': {
#\          'flake8': {
#\            'enabled': 1
#\          },
#\          'mccabe': {
#\            'enabled': 0
#\          },
#\          'pycodestyle': {
#\            'enabled': 0
#\          },
#\          'pyflakes': {
#\            'enabled': 0
#\          },
#\          'Black': {
#\            'enabled': 0
#\          },
#\        }
#\      }
#\    }
#\  }
#\}
#'''
#================ 冬眠 プラグイン ===================
#[[plugins]]
#repo = 'petobens/poet-v'


#[[plugins]]
#repo ='scrooloose/nerdtree'
